return {
	"xiyaowong/transparent.nvim",
	dependencies = {
		"hrsh7th/nvim-cmp",
		-- "savq/melange-nvim",
		-- "folke/tokyonight.nvim",
		-- "catppuccin/nvim",
		-- "rebelot/kanagawa.nvim",
		-- "rose-pine/neovim",
		"edeneast/nightfox.nvim",
		-- "navarasu/onedark.nvim",
		-- "projekt0n/github-nvim-theme",
		-- "sainnhe/everforest",
		-- "mofiqul/vscode.nvim",
		-- "scottmckendry/cyberdream.nvim",
		-- "olimorris/onedarkpro.nvim",
		-- "mofiqul/dracula.nvim",
		-- "marko-cerovac/material.nvim",
		lazy = false,
		priority = 1000,
	},
	config = function()
		vim.cmd("colorscheme carbonfox")
		require("transparent").setup({
			groups = {
				-- "CursorLine",
				-- "CursorLineNr",
				-- "FloatBorder",
				-- "GitSignsAdd",
				-- "GitSignsChange",
				-- "GitSignsDelete",
				-- "LineNr",
				-- "NonText",
				-- "Normal",
				"NormalFloat",
				-- "NormalNC",
				"NvimTreeNormal",
				-- "SignColumn",
				-- "StatusLine",
				-- "StatusLineNC",
			},
			extra_groups = {},
			exclude_groups = {},
		})
	end,
}
